
package mff.betse.nswi145.food_delivery_app.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.5.11
 * Sun Mar 23 01:38:21 CET 2025
 * Generated source version: 3.5.11
 */

@XmlRootElement(name = "sendOrderRequest", namespace = "http://food_delivery_app.nswi145.betse.mff/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sendOrderRequest", namespace = "http://food_delivery_app.nswi145.betse.mff/")

public class SendOrderRequest {

    @XmlElement(name = "arg0")
    private mff.betse.nswi145.food_delivery_app.OrderRequest arg0;

    public mff.betse.nswi145.food_delivery_app.OrderRequest getArg0() {
        return this.arg0;
    }

    public void setArg0(mff.betse.nswi145.food_delivery_app.OrderRequest newArg0)  {
        this.arg0 = newArg0;
    }

}

