
package mff.betse.nswi145.food_delivery_app;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.11
 * 2025-03-23T01:55:10.289+01:00
 * Generated source version: 3.5.11
 *
 */
public final class IRestaurantOrderService_RestaurantOrderServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://food_delivery_app.nswi145.betse.mff/", "RestaurantOrderServiceImplService");

    private IRestaurantOrderService_RestaurantOrderServiceImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = RestaurantOrderServiceImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        RestaurantOrderServiceImplService ss = new RestaurantOrderServiceImplService(wsdlURL, SERVICE_NAME);
        IRestaurantOrderService port = ss.getRestaurantOrderServiceImplPort();

        {
        System.out.println("Invoking sendOrderRequest...");
        mff.betse.nswi145.food_delivery_app.OrderRequest _sendOrderRequest_arg0 = new mff.betse.nswi145.food_delivery_app.OrderRequest();
        _sendOrderRequest_arg0.setCustomerName("CustomerName658169710");
        java.util.List<mff.betse.nswi145.food_delivery_app.FoodItem> _sendOrderRequest_arg0FoodItems = new java.util.ArrayList<mff.betse.nswi145.food_delivery_app.FoodItem>();
        mff.betse.nswi145.food_delivery_app.FoodItem _sendOrderRequest_arg0FoodItemsVal1 = new mff.betse.nswi145.food_delivery_app.FoodItem();
        _sendOrderRequest_arg0FoodItemsVal1.setName("Name261296465");
        _sendOrderRequest_arg0FoodItemsVal1.setQuantity(-122959048);
        _sendOrderRequest_arg0FoodItems.add(_sendOrderRequest_arg0FoodItemsVal1);
        _sendOrderRequest_arg0.getFoodItems().addAll(_sendOrderRequest_arg0FoodItems);
        _sendOrderRequest_arg0.setOrderId("OrderId1183137178");
        java.lang.String _sendOrderRequest__return = port.sendOrderRequest(_sendOrderRequest_arg0);
        System.out.println("sendOrderRequest.result=" + _sendOrderRequest__return);


        }
        {
        System.out.println("Invoking checkOrderStatus...");
        java.lang.String _checkOrderStatus_arg0 = "_checkOrderStatus_arg0658241989";
        java.lang.String _checkOrderStatus__return = port.checkOrderStatus(_checkOrderStatus_arg0);
        System.out.println("checkOrderStatus.result=" + _checkOrderStatus__return);


        }

        System.exit(0);
    }

}
