package mff.betse.nswi145.food_delivery_app;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.11
 * 2025-03-23T01:55:10.336+01:00
 * Generated source version: 3.5.11
 *
 */
@WebService(targetNamespace = "http://food_delivery_app.nswi145.betse.mff/", name = "IRestaurantOrderService")
@XmlSeeAlso({ObjectFactory.class})
public interface IRestaurantOrderService {

    @WebMethod(action = "urn:SendOrderRequest")
    @RequestWrapper(localName = "sendOrderRequest", targetNamespace = "http://food_delivery_app.nswi145.betse.mff/", className = "mff.betse.nswi145.food_delivery_app.SendOrderRequest")
    @ResponseWrapper(localName = "sendOrderRequestResponse", targetNamespace = "http://food_delivery_app.nswi145.betse.mff/", className = "mff.betse.nswi145.food_delivery_app.SendOrderRequestResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String sendOrderRequest(

        @WebParam(name = "arg0", targetNamespace = "")
        mff.betse.nswi145.food_delivery_app.OrderRequest arg0
    );

    @WebMethod(action = "urn:CheckOrderStatus")
    @RequestWrapper(localName = "checkOrderStatus", targetNamespace = "http://food_delivery_app.nswi145.betse.mff/", className = "mff.betse.nswi145.food_delivery_app.CheckOrderStatus")
    @ResponseWrapper(localName = "checkOrderStatusResponse", targetNamespace = "http://food_delivery_app.nswi145.betse.mff/", className = "mff.betse.nswi145.food_delivery_app.CheckOrderStatusResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String checkOrderStatus(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
