package mff.betse.nswi145.food_delivery_app;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.5.11
 * 2025-03-23T01:55:10.341+01:00
 * Generated source version: 3.5.11
 *
 */
@WebServiceClient(name = "RestaurantOrderServiceImplService",
                  wsdlLocation = "http://localhost:8081/cxf-server/wsdl/restaurantorderserviceimpl.wsdl",
                  targetNamespace = "http://food_delivery_app.nswi145.betse.mff/")
public class RestaurantOrderServiceImplService extends Service {

    public static final URL WSDL_LOCATION;

    public static final QName SERVICE = new QName("http://food_delivery_app.nswi145.betse.mff/", "RestaurantOrderServiceImplService");
    public static final QName RestaurantOrderServiceImplPort = new QName("http://food_delivery_app.nswi145.betse.mff/", "RestaurantOrderServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8081/cxf-server/wsdl/restaurantorderserviceimpl.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(RestaurantOrderServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8081/cxf-server/wsdl/restaurantorderserviceimpl.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public RestaurantOrderServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public RestaurantOrderServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RestaurantOrderServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public RestaurantOrderServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public RestaurantOrderServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public RestaurantOrderServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns IRestaurantOrderService
     */
    @WebEndpoint(name = "RestaurantOrderServiceImplPort")
    public IRestaurantOrderService getRestaurantOrderServiceImplPort() {
        return super.getPort(RestaurantOrderServiceImplPort, IRestaurantOrderService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IRestaurantOrderService
     */
    @WebEndpoint(name = "RestaurantOrderServiceImplPort")
    public IRestaurantOrderService getRestaurantOrderServiceImplPort(WebServiceFeature... features) {
        return super.getPort(RestaurantOrderServiceImplPort, IRestaurantOrderService.class, features);
    }

}
