
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package mff.betse.nswi145.food_delivery_app;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.11
 * 2025-03-23T01:55:10.327+01:00
 * Generated source version: 3.5.11
 *
 */

@javax.jws.WebService(
                      serviceName = "RestaurantOrderServiceImplService",
                      portName = "RestaurantOrderServiceImplPort",
                      targetNamespace = "http://food_delivery_app.nswi145.betse.mff/",
                      wsdlLocation = "http://localhost:8081/cxf-server/wsdl/restaurantorderserviceimpl.wsdl",
                      endpointInterface = "mff.betse.nswi145.food_delivery_app.IRestaurantOrderService")

public class RestaurantOrderServiceImplPortImpl implements IRestaurantOrderService {

    private static final Logger LOG = Logger.getLogger(RestaurantOrderServiceImplPortImpl.class.getName());

    /* (non-Javadoc)
     * @see mff.betse.nswi145.food_delivery_app.IRestaurantOrderService#sendOrderRequest(mff.betse.nswi145.food_delivery_app.OrderRequest arg0)*
     */
    public java.lang.String sendOrderRequest(mff.betse.nswi145.food_delivery_app.OrderRequest arg0) {
        LOG.info("Executing operation sendOrderRequest");
        System.out.println(arg0);
        try {
            java.lang.String _return = "_return-1204601117";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see mff.betse.nswi145.food_delivery_app.IRestaurantOrderService#checkOrderStatus(java.lang.String arg0)*
     */
    public java.lang.String checkOrderStatus(java.lang.String arg0) {
        LOG.info("Executing operation checkOrderStatus");
        System.out.println(arg0);
        try {
            java.lang.String _return = "_return-1148165731";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
